{
 "title": "Haproxy Monitoring - Per Proxy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "customer_name", "label": "Customer Name", "query": { "query": "label_values(customer-name)" } },
   {
    "name": "haproxy_name",
    "label": "HAproxy Name",
    "query": {
     "query": "label_values(haproxy_frontend_bytes_in_total{\"customer-name\"=~\"$customer_name\"},haproxy-name)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,2m,3m,4m,5m,10m,15m,30m,1h,3h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Bytes In",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(haproxy_backend_bytes_in_total{proxy=\"lb_backend\", \"customer-name\"=~\"$customer_name\", \"haproxy-name\"=~\"$haproxy_name\"}[$interval])",
     "legendFormat": "byte in total"
    }
   ]
  },
  {
   "title": "Rate Byte In ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(haproxy_backend_bytes_in_total{proxy=\"lb_backend\", \"customer-name\"=~\"$customer_name\", \"haproxy-name\"=~\"$haproxy_name\"}[$interval])",
     "legendFormat": "byte in total"
    }
   ]
  },
  {
   "title": "Total Bytes Out",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(haproxy_backend_bytes_out_total{proxy=\"lb_backend\", \"customer-name\"=~\"$customer_name\", \"haproxy-name\"=~\"$haproxy_name\"}[$interval])",
     "legendFormat": "byte out total"
    }
   ]
  },
  {
   "title": "Rate Byte Out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(haproxy_backend_bytes_out_total{proxy=\"lb_backend\", \"customer-name\"=~\"$customer_name\", \"haproxy-name\"=~\"$haproxy_name\"}[$interval])",
     "legendFormat": "byte out total"
    }
   ]
  }
 ]
}